### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by nzxt** [cmp-cc/vue-cookies#1]
Thanks for plugin first!

Fix three typos in readme.md file for **$cookies**:

> Remove a cookie
> this.$cookie**s**.remove(name[, path],domain)
> Exist a cookie name
> this.**$**cookie**s**.isKey(keyName) // return boolean
> Get All cookie name(KeyName)
> this.**$**cookie**s**.keys()  // return a array

**Comment by cmp-cc** [comment]
thx
