### ISSUE TITLE
remove cookie disable

### ISSUE THREAD

**Issue by xcheese** [cmp-cc/vue-cookies#10]
![image](https://user-images.githubusercontent.com/9137396/37712165-06f51cbe-2d4e-11e8-8e44-7eadcecf8720.png)

**Comment by cmp-cc** [comment]
test: no problem
https://jsfiddle.net/cmpcc/rLnbwsvg/6/

 I need more information

**Comment by akizor** [comment]
I experienced similar case and as @spcbeck stated, managed to solve it by specifically putting the `path` value to `/` when setting and removing the cookies.

**Comment by cmp-cc** [comment]
@spcbeck @akizor 
path to '',default browser. path=current path. Other paths cannot be remove

v1.5.7,  default path=/ , restore browser defaults through `config` method

```
// 30 day after, expire, '' current path , browser default
[this | Vue | window].$cookies.config('30d','')
```

**Comment by thEpisode** [comment]
I had the same problem, but I change to current version and problem was solved.
