### ISSUE TITLE
Error in example 

### ISSUE THREAD

**Issue by ajhaupt7** [cmp-cc/vue-cookies#11]
In the usage example it says: `import Vue from 'Vue'`. 

This is a typo that will lead to the following error during compilation:
```
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing.
```

It should read `import Vue from 'vue'`

**Comment by cmp-cc** [comment]
thank u
