### ISSUE TITLE
set domain

### ISSUE THREAD

**Issue by mingaohello** [cmp-cc/vue-cookies#15]
// set domain
this.$cookies.set("use_path_argument","value",null, null, "domain.com");   // default 1 day after,expire
失败，域名还是没变

**Comment by cmp-cc** [comment]
Domain 标识定义了Cookie的作用域：Cookie应该发送给哪些URL。


#### 无法跨域Cookie设置

我们將Cookie发送给github.com `this.$cookies.set('key',value,expire,null,'github.com')`，那么github.com站点下就会出现指定cookie。

我们把这种设置除当前域名或者其父域名之外的其他domain，叫做： 跨域Cookie设置。

现代浏览器出于安全性的考虑，防止不同网站之间进行`跨域攻击`,禁止了`跨域Cookie设置`,除此之外还无法进行域名向上传递设置


#### 无法进行向上传递设置

当前域名: example.com  
一级域名只能设置domain为一级域名，不能设置为二级域名或者三级域名等等，否则cookie无法生成。

```
this.$cookies.set('key',value,expire,null,'sub.example.com') // invalid/无效的
this.$cookies.set('key',value,expire,null,'sub.sub.example') // invalid/无效的
```

#### 如何使用Cookie中的domain

- 不指定或设置为当前域名
Domain 标识指定了哪些主机可以接受Cookie。如果不指定，默认为当前文档的主机（不包含子域名,部分浏览器不指定子域名也会存在）。如果指定了Domain，则一般包含子域名。
- 向下传递
`sub.sub.example.com` 设置`this.$cookies.set('key',value,expire,null,'sub.example.com')` 或 `this.$cookies.set('key',value,expire,null,'example.com')`是有效的
