### ISSUE TITLE
Can't set expiry

### ISSUE THREAD

**Issue by mbarwick83** [cmp-cc/vue-cookies#2]
I can't seem to set the expiry. Without it, it works fine.

````this.$cookies.set('name',` 'value', 1);````

**Comment by cmp-cc** [comment]
Thank you very much for driving me

expiry testing  is valid.

```
VueCookies.set("TestNumber","5s Later,expiry",5);

var timer = setInterval(function(){
   if(VueCookies.isKey("TestNumber")){
     console.log(VueCookies.get("TestNumber"))
   } else {
    console.log("cookie name: TestNumber not find\t", VueCookies.get("TestNumber"))
    clearInterval(timer)
   }
},1 * 1000)

```
results
```
5s Later,expiry  
5s Later,expiry
5s Later,expiry
5s Later,expiry       
VM821:7 cookie name: TestNumber not find	 null
```
In line with expectations
- ---

this.$cookies.set('name',` 'value', 1);      // 1 second later,  expiry

this.$cookies.set('name',` 'value', 60);      // 1 minute later,  expiry

this.$cookies.set('name',` 'value', new Date(2018, 1, 1));      // 2018 yeas,  expiry

this.$cookies.set('name',` 'value', "Mon, 01 Jan 2018 12:00:00 GMT");  // input a string

**Comment by cmp-cc** [comment]
my argument named,  to mislead you. I'm sorry
