### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by ben-Run** [cmp-cc/vue-cookies#26]
version mismatch
![image](https://user-images.githubusercontent.com/17672822/50326768-06f39180-0527-11e9-9a8b-2c3735c8e393.png)
use: npm info vue-cookie
![image](https://user-images.githubusercontent.com/17672822/50326794-2db1c800-0527-11e9-9ab6-5af04fa05906.png)

**Comment by cmp-cc** [comment]
```
npm info vue-cookies

npm install -S vue-cookies
```

**Comment by ben-Run** [comment]
oh ！！！ is vue-cookies 。

**Comment by ben-Run** [comment]
is vue-cookies
