### ISSUE TITLE
Delete all cookies

### ISSUE THREAD

**Issue by FreddyCrugger** [cmp-cc/vue-cookies#28]
Hello,

How do we delete all the cookies at once, do you have a function or do we have to create our own?

Thank you

**Comment by cmp-cc** [comment]
```
[this | Vue | window].$cookies.keys().forEach(cookie => [this | Vue | window].$cookies.remove(cookie))
```

Do you have any good Suggestions.

**Comment by FreddyCrugger** [comment]
Brilliant! Thank you so much.
