### ISSUE TITLE
SameSite attribute?

### ISSUE THREAD

**Issue by alexivaylov** [cmp-cc/vue-cookies#33]
I was unable to find an example on how to set the attribute “SameSite”. Is it possible to set it globally in the config? 

What about per-cookie basis?

Many thanks

**Comment by cmp-cc** [comment]
not support  to set the attribute `SameSite`. use default value

SameSite attribute value :
- Strict (default, Apply to all)
- Lax

Not all browsers actually support it: 

![image](https://user-images.githubusercontent.com/5979185/56953654-9eb95a00-6b6f-11e9-94d2-de8569fd69d8.png)

**Comment by skix123** [comment]
Hi, please provide `SameSite` flag, [only IE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility) doesn't support it.

**Comment by DazDotOne** [comment]
@cmp-cc chrome has started issuing the following message:

> A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

Just thought I'd make you aware.

Thanks.

**Comment by MichMich** [comment]
Same issue here. Chrome is giving a warning.

**Comment by cmp-cc** [comment]
Chrome is giving a warning.

fix v1.7.3

**Comment by danielHype** [comment]
Chrome is blocking.
