### ISSUE TITLE
Improve docs for .remove()

### ISSUE THREAD

**Issue by ivaneidel** [cmp-cc/vue-cookies#34]
We are building a site that uses the same login page for multiple subdomains and we were struggling with the logout action, after inspecting source code of the remove function we realised that if you don't use the same parameters for creating and deleting the cookie, it won't work.
Example:
```
window.$cookies.set("token", value, null, null, "domain.com");
```
this would not work:
```
window.$cookies.remove("token");
```
you need to do:
```
window.$cookies.remove("token", null, "domain.com");
```

Great library! Keep up the good work

**Comment by olasunkanmi04** [comment]
> We are building a site that uses the same login page for multiple subdomains and we were struggling with the logout action, after inspecting source code of the remove function we realised that if you don't use the same parameters for creating and deleting the cookie, it won't work.
> Example:
> 
> ```
> window.$cookies.set("token", value, null, null, "domain.com");
> ```
> 
> this would not work:
> 
> ```
> window.$cookies.remove("token");
> ```
> 
> you need to do:
> 
> ```
> window.$cookies.remove("token", null, "domain.com");
> ```
> 
> Great library! Keep up the good work

@ivaneidel Were you able to delete/remove the cookies from the subdomains? Because I am having a similar issue and I can't seem to delete cookies created in domain.com while in sub.domain.com

**Comment by ivaneidel** [comment]
> > We are building a site that uses the same login page for multiple subdomains and we were struggling with the logout action, after inspecting source code of the remove function we realised that if you don't use the same parameters for creating and deleting the cookie, it won't work.
> > Example:
> > ```
> > window.$cookies.set("token", value, null, null, "domain.com");
> > ```
> > 
> > 
> > this would not work:
> > ```
> > window.$cookies.remove("token");
> > ```
> > 
> > 
> > you need to do:
> > ```
> > window.$cookies.remove("token", null, "domain.com");
> > ```
> > 
> > 
> > Great library! Keep up the good work
> 
> @ivaneidel Were you able to delete/remove the cookies from the subdomains? Because I am having a similar issue and I can't seem to delete cookies created in domain.com while in sub.domain.com

Hi @olasunkanmi04, yes, we did actually delete the cookies following the code here, but the thing to note is that you have to add a dot '.' when you are setting the cookie and when you are deleting it. We wanted to logout from all the subdomains at the same time, so we ended up writing it like this:

```
// Login
window.$cookies.set("token", value, timeToLive, null, ".domain.com");

// Logout
window.$cookies.remove("token", null, ".domain.com");

```

**Comment by olasunkanmi04** [comment]
> > > We are building a site that uses the same login page for multiple subdomains and we were struggling with the logout action, after inspecting source code of the remove function we realised that if you don't use the same parameters for creating and deleting the cookie, it won't work.
> > > Example:
> > > ```
> > > window.$cookies.set("token", value, null, null, "domain.com");
> > > ```
> > > 
> > > 
> > > this would not work:
> > > ```
> > > window.$cookies.remove("token");
> > > ```
> > > 
> > > 
> > > you need to do:
> > > ```
> > > window.$cookies.remove("token", null, "domain.com");
> > > ```
> > > 
> > > 
> > > Great library! Keep up the good work
> > 
> > 
> > @ivaneidel Were you able to delete/remove the cookies from the subdomains? Because I am having a similar issue and I can't seem to delete cookies created in domain.com while in sub.domain.com
> 
> Hi @olasunkanmi04, yes, we did actually delete the cookies following the code here, but the thing to note is that you have to add a dot '.' when you are setting the cookie and when you are deleting it. We wanted to logout from all the subdomains at the same time, so we ended up writing it like this:
> 
> ```
> // Login
> window.$cookies.set("token", value, timeToLive, null, ".domain.com");
> 
> // Logout
> window.$cookies.remove("token", null, ".domain.com");
> ```
> 
> Hope this helps you.
> 
> Cheers!

Awesome, thank you.
That fixed the issue I was having.

I appreciate
