### ISSUE TITLE
Secure Cookie Not being Set

### ISSUE THREAD

**Issue by joemaramdocs** [cmp-cc/vue-cookies#37]
Hello i am setting my Cookies like this.on the HTTP/else it is working and setting a cookie while on my HTTPS server its not setting any cookies.

`        if (window.location.protocol == "https:"){
           this.$cookies.set("firstName", "Jer", "1d",window.location.hostname,true);
          this.$cookies.set("lastName", "Sample", "1d",window.location.hostname,true);
          this.$cookies.set("companyName", "Sample Comp", "1d",window.location.hostname,true);
          this.$cookies.set("companyID", "VIP", "1d",window.location.hostname,true);
        }else{
          this.$cookies.set("firstName", "Jer", "1d",window.location.hostname);
          this.$cookies.set("lastName", "Sample", "1d",window.location.hostname);
          this.$cookies.set("companyName", "Sample Comp", "1d",window.location.hostname);
          this.$cookies.set("companyID", "VIP", "1d",window.location.hostname);
        }`

**Comment by cmp-cc** [comment]
`$cookies.set(keyName, value[, expireTimes[, path[, domain[, secure]]]])`

```
this.$cookies.set("firstName", "Jer", "1d","/",window.location.hostname,true);
```

**Comment by joemaramdocs** [comment]
its not working :(

**Comment by joemaramdocs** [comment]
Working now change "/" to null
