### ISSUE TITLE
$cookies.config supports the 'domain [, secure]' parameter

### ISSUE THREAD

**Issue by 1107115073** [cmp-cc/vue-cookies#40]
Will the $cookies.config method support the "domain [, secure]" parameter later.

**example:** 
before: $cookies.config(expireTimes[,path])
after: $cookies.config(expireTimes[, path[, domain[, secure]]])

**Comment by cmp-cc** [comment]
Published in v1.5.14

**Comment by cmp-cc** [comment]
Published in v1.6.0
