### ISSUE TITLE
vue 2.6.10 typescript

### ISSUE THREAD

**Issue by sysmat** [cmp-cc/vue-cookies#41]
"vue-cookies": "^1.5.14",
"vue": "^2.6.10",
"vue-class-component": "^7.1.0",

gives eror:

` Property 'install' is missing in type 'VueCookies' but required in type 'PluginObject<any>'.`

**Comment by cmp-cc** [comment]
try "vue-cookies": "1.5.13" . Whether there is the same problem. tell me.

**Comment by cmp-cc** [comment]
updated to v1.6.0
```
npm remove vue-cookies
npm install vue-cookies --save
```
