### ISSUE TITLE
V1.6.0 needs to improve remove()

### ISSUE THREAD

**Issue by 1107115073** [cmp-cc/vue-cookies#42]
Global configuration:
```
$cookies.config("0", "/", "domain.com");
```

When the web runs on a.domain.com.
```
$cookies.set("k1", "v1");
$cookies.remove("k1");   // this will not delete K1.
```

you need to do:
```
$cookies.remove("k1", null, "domain.com");
```

The reason is：
```
remove: function(key, path, domain) {
            if (!key || !this.isKey(key)) {
                return false;
            }
           // defaultconfig.domain is not considered in domain processing
            document.cookie = encodeURIComponent(key) + "=; expires=Thu, 01 Jan 1970 00:00:00 GMT" + (domain ? "; domain=" + domain : "") + (path ? "; path=" + path : defaultConfig.path);
            return this;
},
```

**Comment by cmp-cc** [comment]
updated to v1.6.1

**Comment by 1107115073** [comment]
Thank&nbsp;you&nbsp;very&nbsp;much&nbsp;for&nbsp;your&nbsp;help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cmp-cc"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 下午4:44
收件人:&nbsp;"cmp-cc/vue-cookies"<vue-cookies@noreply.github.com&gt;;
抄送:&nbsp;"梦年"<1107115073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cmp-cc/vue-cookies] V1.6.0 needs to improve remove() (#42)




updated to v1.6.1
