### ISSUE TITLE
1.6.1 throws Uncaught TypeError: Cannot read property 'isKey' of undefined

### ISSUE THREAD

**Issue by dasmikko** [cmp-cc/vue-cookies#43]
After updating to 1.6.1, it throws the error:
Uncaught TypeError: Cannot read property 'isKey' of undefined

**Comment by cmp-cc** [comment]
Check the syntax

[this | Vue].$cookies.[method]

**Comment by dasmikko** [comment]
Did the syntax change from 1.5.13 to 1.6.1?

**Comment by cmp-cc** [comment]
syntax no change

Print operation statement，I want to know more

**Comment by dasmikko** [comment]
I'm unsure of what you want

**Comment by cmp-cc** [comment]
error position, show code

**Comment by cmp-cc** [comment]
sorry，not load image.  
switch to v1.5.13

1.6.1 change to $cookies

**Comment by dasmikko** [comment]
Alright, thanks
