### ISSUE TITLE
doesn't work with base64 value for cookie

### ISSUE THREAD

**Issue by danirocha** [cmp-cc/vue-cookies#45]
When I tried to set a base64 value for my cookie with this lib, the cookie got wrongly encoded. The `=` sign was replaced by its code `%3D` and when I tried to decode it with js function `atob()`, it didn't work.

Do we have a `setRawCookie` at the lib so things like this wouldn't happen?

**Comment by cmp-cc** [comment]
You can show your code. I want to know the details
```
var btoaValue = btoa('https://semver.org/lang/id/spec/v2.0.0.html');  // Base64 encoded
$cookies.set('base64',btoaValue); // encodeURIComponent
btoaValue  = $cookies.get('base64') // decodeURIComponent

console.log(atob(btoaValue)); // -> https://semver.org/lang/id/spec/v2.0.0.html
```

**Comment by dumedeiros** [comment]
I'm having the same problem than @danirocha.
I, for example, wanna create the following cookie:
Vue.$cookies.set('example', "**user=myself**")
The stored cookie becomes **user%3Dmyself**, but I want it to be exactly as **user=myself**
