### ISSUE TITLE
Cookie not working on iOS

### ISSUE THREAD

**Issue by pascalicchio** [cmp-cc/vue-cookies#47]
Hey guys,

vue-cookies  works nice for my Android project but it doesn't  on iOS.

Does anyone had the same problem?

**Comment by Tofandel** [comment]
It's very likely a regex issue in this lib..

**Comment by goatandsheep** [comment]
I'm having an issue. It checks it properly and saves the cookies, but when you change the page and return, it no longer remains

**Comment by goatandsheep** [comment]
@pascalicchio I'm no longer having this issue. I recommend you double check with your project. Maybe we can close this ticket
