### ISSUE TITLE
remove cookie from browser

### ISSUE THREAD

**Issue by mangrove108** [cmp-cc/vue-cookies#58]
Hello there, after updating to vue-cookies 1.7.1  i couldnt no longer remove a cookie from the browser using nuxt v2.13.3 
in ssr mode, universal app. Had to downgrade to 1.7.0 couldnt find the reason why. `window.$cookies.remove('dark-cookie');`

**Comment by cmp-cc** [comment]
use 1.7.0 or 1.7.2,please

this is a bug ,  sorry
