### ISSUE TITLE
this.$cookies is undefined

### ISSUE THREAD

**Issue by MarcBacordio** [cmp-cc/vue-cookies#6]
main.js:

import VueCookies from 'vue-cookies'
Vue.use (VueCookies)

this.$cookies.set('name', 'trial')

error in console: this.$cookies is undefined

**Comment by cmp-cc** [comment]
`this` scope of Vue Object
eg :
```
 export default{ 
      data() {
          return {
                ....
           }
     },
    created:function() { 
        this.$cookies(key,value,expire)
     }
 }
```
- ---
global scope use window.set(key,value,expire)
