### ISSUE TITLE
Checking For Existent Cookie Returning False

### ISSUE THREAD

**Issue by ryan-gilb** [cmp-cc/vue-cookies#7]
Hi! Thank you for contributing this awesome module to work with cookies in Vue. I'm having an issue where calling `this.$cookies.isKey('clientID')` where `clientID` is the name of my cookie is always returning false, even though the cookie is set and I am verifying it in my dev tools. For a little more context, I'm checking for this cookie inside of a method in the `methods` property in a Vue component, and it is being called as the value of a `v-if` directive in a span. I would appreciate any pointers on resolving this issue, thanks!

**Comment by rgilbert1** [comment]
Also, calling `this.$cookies.keys()` returns `[""]`.

**Comment by cmp-cc** [comment]
thank u ,  I try to restore, base description

https://jsfiddle.net/cmpcc/q8ja3aew/4/

**Comment by cmp-cc** [comment]
this.$cookies.keys() returns [""].  fix of v.1.5.5    Thank yon very much
