### ISSUE TITLE
window.$cookies.get('cookie-name')  // what if I have many cookies with same name?

### ISSUE THREAD

**Issue by JosielFaleiros** [cmp-cc/vue-cookies#8]
My question is, what if I have many cookies in the same domain, but in different paths, how would I get a token from a specif path using vue-cookies?
I ask this, because when I try to do so, the `window.$cookies.get('cookie-name') ` returns just the cookie in the path were it was called from and not the one with same name but in different paths.
I still tried `window.$cookies.get('cookie-name', '/specific-path')` but same result.

Thanks for your attention, and awesome contribution with vue-cookies :D

**Comment by cmp-cc** [comment]
thank u very much

not support, now
https://stackoverflow.com/questions/32579803/how-to-get-cookies-path-using-javascript

#### spa temporary solution
https://jsfiddle.net/cmpcc/Lcu71h5n/43/

#### multiple page  dev
```
  window.$cookies.set("cookie-name","lock_e.3421.h.1","24d","/home/");
  window.$cookies.set("cookie-name","lock_e.3421.h.2","24d","/news/");
```
```
   window.$cookies.get("cookie-name")  
in /home path ：lock_e.3421.h.1
in /news  path ：lock_e.3421.h.2
```
