### ISSUE TITLE
Inject() can only be used inside setup() or functional components

### ISSUE THREAD

**Issue by milan-shops-united** [cmp-cc/vue-cookies#86]
I have the below code in a function in a ts file. When I call the function from a vue component then everything works fine. But when I call the function from another ts file like the main.ts in a Vue project then it won't work. 
`const cookies = inject<VueCookies>('$cookies');`

`console.log(cookies)`
Output from main.ts: 
`undefined`

Output from a Vue component:
`{install: ƒ, config: ƒ, get: ƒ, set: ƒ, remove: ƒ, …}`

The below warning wil appear: 
`[Vue warn]: inject() can only be used inside setup() or functional components.`

Is there an another way to let this works? 

Below code will work but IDE give the red wavy line
![Screenshot 2022-12-13 at 16 57 46](https://user-images.githubusercontent.com/114927330/207381894-fbac16d3-0eea-44cb-b669-3d4e4a88f0b6.png)

**Comment by cmp-cc** [comment]
*  Recommended in App.vue context
```
import { createApp } from 'vue'
import App from './App.vue'

import VueCookies from 'vue-cookies'

createApp(App)
    .use(VueCookies, { expires: '1d' })
    .mount('#app')
```
* use VueCookies
```
createApp(App)
    .use(VueCookies, { expires: '1d' })
    .mount('#app')

VueCookies.get / set
```
* Black Magic [windows object]
```
createApp(App)
    .use(VueCookies, { expires: '1d' })
    .mount('#app')

window.$cookies.get/set
```
