### ISSUE TITLE
so many errors in document?

### ISSUE THREAD

**Issue by playboygit** [cmp-cc/vue-cookies#9]
1. API shold use before:  this.$cookie, not this.$cookies
2.remove cookie shold use this.$cookie.delete(),not this.$cookie.remove()
3.set expire times can not use,now I only use number time, it's default time unit is day, not second

**Comment by cmp-cc** [comment]
api all:  [this | Vue | window].$cookies.[method]
 ```
this.$cookies.set(keyName, value[, expireTimes[, path[, domain[, secure]]]]) 
this.$cookies.isKey("token")
this.$cookies.get("token");
this.$cookies.remove("token");
this.$cookies.keys(); 
```

你可以使用中文， 经过测试 set `expire times`  没有异常。

**Comment by playboygit** [comment]
那就用中文吧，api说明确实有问题，我参照说明用npm装的
this.$cookies后面的s不能用，我都是this.$cookie才生效
remove方法不能用，只能用delete方法，我看来源码，源码也是delete方法，不知道文档为什么写remove方法
设置时间就更古怪了，只能用数字设置时间，字符窜格式的设置的时间就变成session了，而且数据格式设置的时间单位是天，不是秒；
我也是郁闷，难道我用错了？

**Comment by cmp-cc** [comment]
你应该是用错库了,用的其他同名库

```
npm install vue-cookies --save
```

**Comment by playboygit** [comment]
确实我用错了，掉了一个s就用成别的库了，尴尬；
你的库有个bug，源码里面月份的判断的时间_expireTime * 259200，这个掉了一个0，成3天了

**Comment by cmp-cc** [comment]
(●'◡'●)  感谢您的贡献 祝您生活愉快

fix of v1.5.6
